name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Docker Extract
      uses: shrink/actions-docker-extract@v3.0.0
      with:
        image: tiltedphoques/st-reborn-server
        path: /home/server/SkyrimTogetherServer
        destination: /
