name: Extract File from Docker Image

on:
  push:
    branches:
      - main

jobs:
  extract_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Pull Docker Image
      run: docker pull tiltedphoques/st-reborn-server:latest

    - name: Use Docker Extract Action
      uses: shrink/actions-docker-extract@v3.0.0
      with:
        image: tiltedphoques/st-reborn-server:latest
        path: /home/server/.
        destination: dist
    - name: Upload Dist
      uses: actions/upload-artifact@v3
      with:
        path: dist
