name: Extract File from Docker Image

on:
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Trigger the workflow'
        required: true
        default: 'manual'

jobs:
  extract_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Remove Unwanted Files
      run: |
        rm -rf "$GITHUB_WORKSPACE/SkyrimTogetherServer"
        rm -rf "$GITHUB_WORKSPACE/crashpad_handler"
        rm -rf "$GITHUB_WORKSPACE/libSTServer.so"
        rm -rf "$GITHUB_WORKSPACE/libstdc++.so.6"

    - name: Pull Docker Image
      run: docker pull tiltedphoques/st-reborn-server:latest

    - name: Use Docker Extract Action
      uses: shrink/actions-docker-extract@v3.0.0
      with:
        image: tiltedphoques/st-reborn-server:latest
        path: /home/server/.
        destination: $GITHUB_WORKSPACE/

    - name: Commit and Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet || git commit -m "Add extracted files" && git push
